- name: copy mongodb repo
  ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

- name: install mongoDB client
  ansible.builtin.package:
       name: mongodb-org-shell
       state: present

- name: get the catalogue entries count
  ansible.builtin.shell: mongo --host mongodb.joinaiops76.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: entries_count
  when: component == "catalogue"

- name: get the user entries count
  ansible.builtin.shell: mongo --host mongodb.joinaiops76.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: entries_count
  when: component == "user"

  #- name: print trhe count
   #   ansible.builtin.debug:
    #   msg: " product count: {{product_count}}" '''

- name: "load {{component}} data"
  ansible.builtin.shell: "mongo --host mongodb.joinaiops76.online < /app/schema/{{component}}.js"
  when: entries_count.stdout == "0"